-- 1. Which category generates highest revenue?
SELECT 
       category,
	   ROUND(SUM(purchase_amount),2) AS highest_revenue
FROM   customer_data
GROUP BY category
ORDER BY highest_revenue DESC
--2. Are discounts actually increasing purchase value?
SELECT 
      discount_applied,
	  ROUND(SUM(purchase_amount),2) AS total_revenue,
	  ROUND(AVG(purchase_amount),2) AS avg_purchase
FROM customer_data
GROUP BY discount_applied
ORDER BY total_revenue DESC 
--3. What is the total revenue generated by male and female customer?
SELECT 
      gender,
	  ROUND(SUM(purchase_amount),2) as highest_revenue
FROM customer_data
GROUP BY gender
ORDER BY highest_revenue DESC

--4. Which  top 10 customers used a discount but still spent more than the average purchase amount?

SELECT 
      customer_id,
	  purchase_amount,
	  discount_applied
FROM customer_data
WHERE discount_applied = 'Yes' AND purchase_amount > (SELECT AVG(purchase_amount) FROM customer_data)
LIMIT 10;

--5. Which are the top/bottom 5 products with the average review rating 
--TOP 5 
SELECT 
      item_purchased,
	  ROUND(AVG(review_rating),2) AS Avg_ratings
FROM customer_data 
GROUP BY item_purchased
ORDER BY Avg_ratings DESC LIMIT 5;
--BOTTOM 5 
SELECT 
      item_purchased,
	  ROUND(AVG(review_rating),2) AS Avg_ratings
FROM customer_data 
GROUP BY item_purchased
ORDER BY Avg_ratings ASC LIMIT 5;

--6. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non - subscribers. 
SELECT 
      subscription_status,
	  COUNT (customer_id) as users, 
	  ROUND(AVG(purchase_amount),2) as avg_revenue,
	  ROUND(SUM(purchase_amount),2) as total_revenue
FROM customer_data
GROUP BY subscription_status
ORDER BY total_revenue DESC

--7. Top 5 products with highest discount usage%
SELECT 
       item_purchased,
	   COUNT(item_purchased) as total_number_of_times_sold,
	   COUNT(CASE WHEN discount_applied ='Yes' THEN 1 END) AS Number_of_times_sold_when_discount_applied,
	   COUNT(CASE WHEN discount_applied ='Yes' THEN 1 END) *100.0 / COUNT(*) AS discount_percent
FROM customer_data
GROUP BY item_purchased 
ORDER BY discount_percent DESC LIMIT 5 
--8. Segment customer into new, returning and loyal based on their total number of previous purchase 
--and show the count of each segment. 
SELECT 
      CASE 
	      WHEN previous_purchase=  '0' THEN 'New Customer'
		  WHEN previous_purchase BETWEEN 1 AND 15 THEN 'Returning Customer'
	  ELSE 'Loyal Customers'
END AS customer_segment,
COUNT(*) AS customer_count
FROM customer_data
GROUP BY CASE 
          WHEN previous_purchase= '0' THEN 'New Customer'
		  WHEN previous_purchase BETWEEN 1 and 15 THEN 'Returning Customer'
ELSE 'Loyal Customers'
END

--9. What are the top 3 most purchased products within each category?
 WITH CTE AS
 (   
 SELECT
       category,
	   item_purchased,
	   COUNT(item_purchased) AS most_purchased,
	   RANK() OVER(PARTITION BY category ORDER BY COUNT(item_purchased) DESC) AS RNK
FROM customer_data
GROUP BY category,item_purchased
)
SELECT * FROM CTE
WHERE RNK <=3
--10 Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe ?

SELECT
      CASE 
	      WHEN previous_purchase >5 THEN 'Repeat Buyers'
		  ELSE 'Normal Buyers'
      END AS customer_type,
	  COUNT(*) AS customer_count,
	  COUNT(*) * 100 / SUM(COUNT(*)) OVER (PARTITION BY CASE 
	                                      WHEN previous_purchase > 5 THEN 'Repeat Buyers'
	                                      ELSE 'Normal Buyers'
	                               END
	                               ) AS percents
	  
	  FROM customer_data
GROUP BY CASE
         WHEN previous_purchase > 5 THEN 'Repeat Buyers'
		 ELSE 'Normal Buyers'
   END, subscription_status
   
--11. What is the revenue contribution of each age group ?
SELECT 
      CASE 
	       WHEN Age BETWEEN 18 AND 25 THEN '18-25'
		   WHEN Age BETWEEN 18 AND 25 THEN '26-35'
		   WHEN Age BETWEEN 18 AND 25 THEN '35-50'
		   ELSE '51+'
		END AS age_group,
		ROUND(SUM(purchase_amount),2) As total_revenue
FROM  customer_data
GROUP BY CASE 
          WHEN Age BETWEEN 18 AND 25 THEN '18-25'
		   WHEN Age BETWEEN 18 AND 25 THEN '26-35'
		   WHEN Age BETWEEN 18 AND 25 THEN '35-50'
		   ELSE '51+'
	END
	ORDER BY total_revenue DESC 
		   