--1. Which product category generates the highest Sales?
SELECT category,
ROUND(SUM(purchase_amount),2) AS total_sales
FROM customer_data
GROUP BY category
ORDER BY total_sales DESC;
--2. Which gender contributes more to overall sales?
SELECT gender,
ROUND(SUM(purchase_amount),2) AS total_sales
FROM customer_data
GROUP BY gender
ORDER BY total_sales DESC;

--3. How are customers distributed across different age groups?
SELECT
      CASE 
	       WHEN age <= 20 THEN '0-20'
		   WHEN age BETWEEN 21 AND 30 THEN '21-30'
		   WHEN age BETWEEN 31 AND 40 THEN '31-40'
		   WHEN age BETWEEN 41 AND 50 THEN '41-50'
		   ELSE '50+'
		   END AS age_group,
		   COUNT(customer_id) AS customer_count
FROM customer_data
GROUP BY age_group
ORDER BY customer_count DESC;
			
--4. Which season records the highest sales?
SELECT season,
Round(SUM(purchase_amount),2) AS total_sales
FROM customer_data
GROUP BY season
ORDER BY total_sales DESC;

--5. Which cities have the highest number of customers?
SELECT  location,
COUNT(customer_id) AS customer_count
FROM customer_data
GROUP BY location
ORDER BY customer_count DESC
LIMIT 5;

--6. Which payment method is mopst preferred by customers?
SELECT payment_method,
COUNT(customer_id) AS total_customers
FROM customer_data
GROUP BY payment_method
ORDER BY total_customers DESC;

--7. What percentage of customers are subscribed?
SELECT subscription_status,
COUNT(customer_id) AS total_customers
FROM customer_data
GROUP BY subscription_status;

--8. Which product categories receive the highest average customer review ratings?

SELECT category,
ROUND(AVG(review_rating),2) AS avg_review_rating
FROM customer_data
GROUP BY category
ORDER BY avg_review_rating DESC;

--9. Which purchase frequency is most common among customers?
SELECT frequency_of_purchases,
COUNT(customer_id) AS customer_count
FROM customer_data
GROUP BY frequency_of_purchases
ORDER BY customer_count DESC;

--10. Which product size is most preferred by customers?
SELECT size,
COUNT(customer_id) AS total_customers
FROM customer_data
GROUP BY size
ORDER BY total_customers DESC;

--11. Which product colors are most preferred?
SELECT color,
COUNT(customer_id) AS total_customers
FROM customer_data
GROUP BY color
ORDER BY total_customers DESC LIMIT 5 ;

--12. Which payment methods genearte the highest sales revenue ?
 SELECT 
       payment_method,
	   ROUND(SUM(purchase_amount),2) AS total_sales
 FROM customer_data
 GROUP BY payment_method
 ORDER BY total_sales DESC LIMIT 5 ;


--13. Which age groups contribute the highest sales revenue?
SELECT 
CASE 
WHEN age <= 20 THEN '0-20'
WHEN age <= 30 THEN '21-30'
WHEN age <= 40 THEN '31-40'
WHEN age <= 50 THEN '41-50'
ELSE '50+'
END AS age_group,
ROUND(SUM(purchase_amount),2) AS total_sales
FROM customer_data
GROUP BY age_group
ORDER BY total_sales DESC;

-- 14. How many total customers are present in the dataset?

SELECT COUNT(DISTINCT customer_id) AS total_customers
FROM customer_data;

--15. How many unique products/items are available?

SELECT COUNT(DISTINCT item_purchased) AS unique_items
FROM customer_data;

--16. What is the average customer review rating?

SELECT ROUND(AVG(review_rating),2) AS avg_review_rating
from customer_data;

--17. What is the total sales revenue generated by the business?

SELECT ROUND(SUM(purchase_amount),2) AS total_sales
FROM customer_data;

--18. What is the average purchase amount per transaction?

SELECT ROUND(AVG(purchase_amount),2) AS avg_purchase
FROM customer_data;